//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace CRMDemoProject.ServiceReference1
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CallCourierReturn", Namespace = "http://schemas.datacontract.org/2004/07/CustCargoInfo.Models")]
    [System.SerializableAttribute()]
    public partial class CallCourierReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int countField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int resultField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultMessageField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int count
        {
            get
            {
                return this.countField;
            }
            set
            {
                if ((this.countField.Equals(value) != true))
                {
                    this.countField = value;
                    this.RaisePropertyChanged("count");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                if ((this.resultField.Equals(value) != true))
                {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultMessage
        {
            get
            {
                return this.resultMessageField;
            }
            set
            {
                if ((object.ReferenceEquals(this.resultMessageField, value) != true))
                {
                    this.resultMessageField = value;
                    this.RaisePropertyChanged("resultMessage");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference1.IArasCargoIntegrationService", SessionMode = System.ServiceModel.SessionMode.NotAllowed)]
    public interface IArasCargoIntegrationService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/GetQueryDS", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/GetQueryDSResponse")]
        System.Data.DataSet GetQueryDS(string loginInfo, string queryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/GetQueryDS", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/GetQueryDSResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetQueryDSAsync(string loginInfo, string queryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/GetQueryXML", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/GetQueryXMLResponse")]
        string GetQueryXML(string loginInfo, string queryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/GetQueryXML", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/GetQueryXMLResponse")]
        System.Threading.Tasks.Task<string> GetQueryXMLAsync(string loginInfo, string queryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/GetQueryJSON", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/GetQueryJSONResponse")]
        string GetQueryJSON(string loginInfo, string queryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/GetQueryJSON", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/GetQueryJSONResponse")]
        System.Threading.Tasks.Task<string> GetQueryJSONAsync(string loginInfo, string queryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/SetDataXML", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/SetDataXMLResponse")]
        string SetDataXML(string loginInfo, string queryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/SetDataXML", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/SetDataXMLResponse")]
        System.Threading.Tasks.Task<string> SetDataXMLAsync(string loginInfo, string queryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/CallCourier", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/CallCourierResponse")]
        CRMDemoProject.ServiceReference1.CallCourierReturn CallCourier(string loginInfo, string queryInfo);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IArasCargoIntegrationService/CallCourier", ReplyAction = "http://tempuri.org/IArasCargoIntegrationService/CallCourierResponse")]
        System.Threading.Tasks.Task<CRMDemoProject.ServiceReference1.CallCourierReturn> CallCourierAsync(string loginInfo, string queryInfo);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArasCargoIntegrationServiceChannel : CRMDemoProject.ServiceReference1.IArasCargoIntegrationService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArasCargoIntegrationServiceClient : System.ServiceModel.ClientBase<CRMDemoProject.ServiceReference1.IArasCargoIntegrationService>, CRMDemoProject.ServiceReference1.IArasCargoIntegrationService
    {

        public ArasCargoIntegrationServiceClient()
        {
        }

        public ArasCargoIntegrationServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ArasCargoIntegrationServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ArasCargoIntegrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ArasCargoIntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Data.DataSet GetQueryDS(string loginInfo, string queryInfo)
        {
            return base.Channel.GetQueryDS(loginInfo, queryInfo);
        }

        public System.Threading.Tasks.Task<System.Data.DataSet> GetQueryDSAsync(string loginInfo, string queryInfo)
        {
            return base.Channel.GetQueryDSAsync(loginInfo, queryInfo);
        }

        public string GetQueryXML(string loginInfo, string queryInfo)
        {
            return base.Channel.GetQueryXML(loginInfo, queryInfo);
        }

        public System.Threading.Tasks.Task<string> GetQueryXMLAsync(string loginInfo, string queryInfo)
        {
            return base.Channel.GetQueryXMLAsync(loginInfo, queryInfo);
        }

        public string GetQueryJSON(string loginInfo, string queryInfo)
        {
            return base.Channel.GetQueryJSON(loginInfo, queryInfo);
        }

        public System.Threading.Tasks.Task<string> GetQueryJSONAsync(string loginInfo, string queryInfo)
        {
            return base.Channel.GetQueryJSONAsync(loginInfo, queryInfo);
        }

        public string SetDataXML(string loginInfo, string queryInfo)
        {
            return base.Channel.SetDataXML(loginInfo, queryInfo);
        }

        public System.Threading.Tasks.Task<string> SetDataXMLAsync(string loginInfo, string queryInfo)
        {
            return base.Channel.SetDataXMLAsync(loginInfo, queryInfo);
        }

        public CRMDemoProject.ServiceReference1.CallCourierReturn CallCourier(string loginInfo, string queryInfo)
        {
            return base.Channel.CallCourier(loginInfo, queryInfo);
        }

        public System.Threading.Tasks.Task<CRMDemoProject.ServiceReference1.CallCourierReturn> CallCourierAsync(string loginInfo, string queryInfo)
        {
            return base.Channel.CallCourierAsync(loginInfo, queryInfo);
        }
    }
}
